source 'https://rubygems.org'

gem 'rails', '~> 5.2.0'
gem 'pg', '~> 1.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'listen'

group :development, :test do
  gem 'rspec-rails', '~> 3.5'
  gem 'capybara', '~> 2.15'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'launchy'
  gem 'pry-rails'
end

group :development do
  gem 'web-console'
end
