---
title: "Nested Routes: Going Camping"
type: "exercise"
behaviors:
  - rails
  - ruby_and_rspec
  - capybara
description: "Help the EE Team go on a camping trip!"
tags: "rails, nested-routes"
ignore:
  - "nested-routes-going-camping.md"
