---
title: "Introduction to Methods"
type: "video"
description: "Study method definitions, return values, arguments and parameters"
tags: "methods, return values, method definitions, arguments, parameters"
ignore:
- "introduction-to-methods.md"
